baseURL = "https://aoblex.github.io/"
title = "trytry's blog"
locale = "en"
timeZone = "Asia/Shanghai"
theme = ["hugo-admonitions", "PaperMod"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[params]
math = true
mainSections = ["posts"]
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowShareButtons = false
ShowToc = true

[params.profileMode]
enabled = true
title = "trytry's home"
subtitle = "Hi there!"
imageUrl = "images/profile.jpg"
imageTitle = "Chenrui Wang"
imageWidth = 150
imageHeight = 150

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[params.profileMode.buttons]]
name = "Archives"
url = "/archives"

[[params.profileMode.buttons]]
name = "Search"
url = "/search"

[menus]
# Hugo menus: https://gohugo.io/configuration/menus/

[[menus.main]]
name = "Posts"
pageRef = "/posts"
weight = 10

[[menus.main]]
name = "Archives"
pageRef = "/archives"
weight = 20

[[menus.main]]
name = "Search"
pageRef = "/search"
weight = 30

[[menus.main]]
name = "About"
pageRef = "/about"
weight = 40
