[tasks.build]
description = "Build the Hugo site"
tools."hugo-extended" = "0.160.0"
run = "hugo build --gc --minify"

[tasks.serve]
description = "Run the local Hugo development server"
tools."hugo-extended" = "0.160.0"
run = "hugo server --buildDrafts"
